/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package adresboek;

import java.awt.event.WindowEvent;
import java.util.Date;
import java.util.List;
import java.util.Observable;
import java.util.Observer;
import javax.swing.SwingUtilities;
import javax.swing.table.DefaultTableModel;

/**
 * @author 6851
 */
public class AdresboekFrame extends javax.swing.JFrame implements Observer {

    /**
     * Creates new form AdresboekFrame
     */
    public AdresboekFrame(Configuration configuration) {
        initComponents();

        final PersoonModel persoonModel = configuration.getPersoonModel();
        persoonModel.addObserver(this);
        addWindowStateListener(e -> {
            if ((e.getNewState() & WindowEvent.WINDOW_CLOSED) != 0) {
                persoonModel.deleteObserver(AdresboekFrame.this);
            }
        });

        jbToevoegen.addActionListener(e -> {
            String voornaam = jtfVoornaam.getText();
            if (voornaam != null && voornaam.length() > 0) {
                Persoon persoon = new Persoon(null, voornaam);
                persoonModel.save(persoon);
                jtfVoornaam.setText("");
            }
        });

        SwingUtilities.invokeLater(() -> persoonModel.refresh());
    }

    @Override
    public void update(Observable o, Object arg) {
        System.out.println("update " + new Date());
        PersoonModel persoonModel = (PersoonModel) o;
        List<Persoon> personen = persoonModel.list();
        DefaultTableModel tableModel = (DefaultTableModel) jtOverzicht.getModel();
        String[][] dataVector = new String[personen.size()][2];
        for (int i = 0; i < personen.size(); i++) {
            Persoon persoon = personen.get(i);
            dataVector[i] = new String[]{"" + persoon.getId(), persoon.getVoornaam()};
        }
        tableModel.setDataVector(dataVector, new String[]{"#", "Voornaam"});
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jbToevoegen = new javax.swing.JButton();
        jtfVoornaam = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtOverzicht = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jbToevoegen.setLabel("Toevoegen");

        jtfVoornaam.setText("Voornaam");

        jtOverzicht.setModel(new javax.swing.table.DefaultTableModel(
                new Object[][]{
                        {null, null, null, null},
                        {null, null, null, null},
                        {null, null, null, null},
                        {null, null, null, null}
                },
                new String[]{
                        "Title 1", "Title 2", "Title 3", "Title 4"
                }
        ));
        jScrollPane1.setViewportView(jtOverzicht);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 605, Short.MAX_VALUE)
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(jbToevoegen)
                                                .addGap(18, 18, 18)
                                                .addComponent(jtfVoornaam, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(0, 0, Short.MAX_VALUE)))
                                .addContainerGap())
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jbToevoegen)
                                        .addComponent(jtfVoornaam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 80, Short.MAX_VALUE)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 358, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdresboekFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdresboekFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdresboekFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdresboekFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdresboekFrame(new Configuration(args)).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbToevoegen;
    private javax.swing.JTable jtOverzicht;
    private javax.swing.JTextField jtfVoornaam;
    // End of variables declaration//GEN-END:variables
}
