/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package adresboek;

import java.awt.event.WindowEvent;
import java.lang.reflect.InvocationTargetException;
import java.util.Date;
import java.util.List;
import java.util.Observable;
import java.util.Observer;
import javax.swing.SwingUtilities;
import javax.swing.table.DefaultTableModel;

/**
 * @author 6851
 */
public class AdresboekFrame extends javax.swing.JFrame implements Observer {

    /**
     * Creates new form AdresboekFrame
     */
    public AdresboekFrame(Configuration configuration) {
        initComponents();

        final PersoonModel persoonModel = configuration.getPersoonModel();
        persoonModel.addObserver(this);
        addWindowStateListener(e -> {
            if ((e.getNewState() & WindowEvent.WINDOW_CLOSED) != 0) {
                persoonModel.deleteObserver(AdresboekFrame.this);
            }
        });

        jbToevoegen.addActionListener(e -> {
            String voornaam = jtfVoornaam.getText();
            if (voornaam != null && voornaam.length() > 0) {
                Persoon persoon = new Persoon(null, voornaam);
                persoonModel.save(persoon);
                jtfVoornaam.setText("");
            }
        });
        jbVerwijderen.addActionListener(e -> {
            persoonModel.delete(persoonModel.getGeselecteerdPersoon());
        });

        jtOverzicht.getSelectionModel().addListSelectionListener(e -> {
            int firstIndex = e.getFirstIndex();
            int lastIndex = e.getLastIndex();
            System.out.println("firstIndex = " + firstIndex);
            System.out.println("lastIndex = " + lastIndex);
            if (!e.getValueIsAdjusting()) {
                persoonModel.selectPersoonByIndex(firstIndex);
            }
        });

        SwingUtilities.invokeLater(() -> persoonModel.refresh());
    }

    @Override
    public void update(Observable o, Object arg) {
        try {
            // dit stuk code werkt de tabel bij, om te zorgen dat niet halverwege de tabel zelf al
            // gaat updaten wordt invokeAndWait() gebruikt:
            SwingUtilities.invokeAndWait(() -> {
                System.out.println("AdresboekFrame.update(...) " + new Date());
                PersoonModel persoonModel = (PersoonModel) o;
                List<Persoon> personen = persoonModel.list();
                DefaultTableModel tableModel = (DefaultTableModel) jtOverzicht.getModel();
                String[][] dataVector = new String[personen.size()][2];
                String geselecteerdPersoonText = null;
                for (int i = 0; i < personen.size(); i++) {
                    Persoon persoon = personen.get(i);
                    dataVector[i] = new String[]{"" + persoon.getId(), persoon.getVoornaam()};
                    Persoon geselecteerdPersoon = persoonModel.getGeselecteerdPersoon();
                    if (persoon.equals(geselecteerdPersoon)) {
                        geselecteerdPersoonText = "#" + persoon.getId() + " " + persoon.getVoornaam();
                    }
                }
                tableModel.setDataVector(dataVector, new String[]{"#", "Voornaam"});
                if (geselecteerdPersoonText == null) {
                    jlGeselecteerdPersoon.setText("");
                    jbVerwijderen.setEnabled(false);
                } else {
                    jlGeselecteerdPersoon.setText(geselecteerdPersoonText);
                    jbVerwijderen.setEnabled(true);
                }
            });
        } catch (InterruptedException | InvocationTargetException e) {
            e.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jbToevoegen = new javax.swing.JButton();
        jtfVoornaam = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtOverzicht = new javax.swing.JTable();
        jbVerwijderen = new javax.swing.JButton();
        jlGeselecteerdPersoon = new javax.swing.JLabel();
        jlVoornaam = new javax.swing.JLabel();
        jlStraat = new javax.swing.JLabel();
        jtfStraat = new javax.swing.JTextField();
        jlHuisnummer = new javax.swing.JLabel();
        jtfHuisnummer = new javax.swing.JTextField();
        jlWoonplaats = new javax.swing.JLabel();
        jtfWoonplaats = new javax.swing.JTextField();
        jtfPostcode = new javax.swing.JTextField();
        jlPostcode = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jbToevoegen.setLabel("Toevoegen");

        jtOverzicht.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jtOverzicht);

        jbVerwijderen.setText("Verwijderen");

        jlVoornaam.setText("Voornaam:");

        jlStraat.setText("Straat:");

        jlHuisnummer.setText("Nr:");

        jlWoonplaats.setText("Woonplaats:");

        jlPostcode.setText("Postcode:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jlGeselecteerdPersoon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbVerwijderen))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jlPostcode)
                                .addGap(8, 8, 8)
                                .addComponent(jtfPostcode, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(14, 14, 14)
                                .addComponent(jlWoonplaats)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jtfWoonplaats))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jlStraat)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                                .addComponent(jtfStraat, javax.swing.GroupLayout.PREFERRED_SIZE, 346, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jlHuisnummer)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jtfHuisnummer, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jlVoornaam)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jtfVoornaam)))
                        .addGap(18, 18, 18)
                        .addComponent(jbToevoegen, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbToevoegen)
                    .addComponent(jtfVoornaam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlVoornaam))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfStraat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlStraat)
                    .addComponent(jtfHuisnummer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlHuisnummer))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfWoonplaats, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlWoonplaats)
                    .addComponent(jtfPostcode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlPostcode))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jbVerwijderen)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jlGeselecteerdPersoon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdresboekFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdresboekFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdresboekFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdresboekFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new AdresboekFrame(new Configuration(args)).setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbToevoegen;
    private javax.swing.JButton jbVerwijderen;
    private javax.swing.JLabel jlGeselecteerdPersoon;
    private javax.swing.JLabel jlHuisnummer;
    private javax.swing.JLabel jlPostcode;
    private javax.swing.JLabel jlStraat;
    private javax.swing.JLabel jlVoornaam;
    private javax.swing.JLabel jlWoonplaats;
    private javax.swing.JTable jtOverzicht;
    private javax.swing.JTextField jtfHuisnummer;
    private javax.swing.JTextField jtfPostcode;
    private javax.swing.JTextField jtfStraat;
    private javax.swing.JTextField jtfVoornaam;
    private javax.swing.JTextField jtfWoonplaats;
    // End of variables declaration//GEN-END:variables
}
